INSERT INTO books (id, rank, title, author, year, pages, notes, film_adaptation, section_type, section_name, section_order, section_subtitle, cluster_vibe, order_in_section)
VALUES
  (189, NULL, 'Minor Detail', 'Adania Shibli', 2017, 105, 'A spare, unsettling Palestinian novel split between a 1949 act of violence and a contemporary woman''s attempt to investigate it. Short, quiet, and devastating, with a strong focus on memory, occupation, and the limits of historical recovery. (via @sunnysbooktruck on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (190, NULL, 'The Witch', 'Marie NDiaye', 1996, 132, 'A strange, slippery novel about a woman with witchlike powers whose daughters seem to be inheriting something mysterious. It blends family breakdown, social discomfort, and the uncanny in a very literary, ambiguous way. (via @sunnysbooktruck on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (191, NULL, 'The Factory', 'Hiroko Oyamada', 2013, 128, 'A deadpan, absurd novella about workers at a massive, baffling factory where the jobs are pointless and reality slowly bends. Good for fans of alienating office novels, Kafkaesque humor, and quiet existential dread. (via @sunnysbooktruck on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (192, NULL, 'Pedro the Vast', 'Simón López Trujillo', 2021, 144, 'A contemporary literary work that appears to sit in a more experimental or international-literary space than commercial fiction. (via @sunnysbooktruck on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (193, NULL, 'This Is How You Lose the Time War', 'Amal El-Mohtar and Max Gladstone', 2019, 208, 'A poetic sci-fi novella about two rival agents on opposite sides of a time-travel war who begin exchanging letters and fall in love. Lush, high-concept, and more emotionally driven than plot-driven. (via @sunnysbooktruck on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (194, NULL, 'Ring Shout', 'P. Djèlí Clark', 2020, 192, 'A supernatural reimagining of the 1920s American South where Ku Klux Klan members are tied to monstrous forces. Fast, sharp, action-heavy, and politically charged, with folk magic, horror, and alternate history. (via @sunnysbooktruck on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;
