INSERT INTO books (id, rank, title, author, year, pages, notes, film_adaptation, section_type, section_name, section_order, section_subtitle, cluster_vibe, order_in_section)
VALUES
  (195, NULL, 'On Earth As It Is Beneath', 'Ana Paula Maia', 2025, 112, 'A stark Brazilian prison novella set in a remote penal colony built on land marked by historical violence. The story turns increasingly brutal and allegorical as the prison''s attempt at "rehabilitation" curdles into ritualized horror. Translated by Padma Viswanathan; published in English by Charco Press. Shortlisted for the International Booker Prize 2026. (via @ohhushreads on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (196, NULL, 'A Wizard of Earthsea', 'Ursula K. Le Guin', 1968, 205, 'A foundational fantasy novel about Ged, a gifted young mage whose pride unleashes a shadow he must eventually face. It is a coming-of-age story, a moral fable, and one of the major ancestors of modern wizard-school and literary fantasy. (via @ohhushreads on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (197, NULL, 'To Be Taught, If Fortunate', 'Becky Chambers', 2019, 160, 'A quiet, humane science-fiction novella about a small crew surveying distant planets and moons. Less space opera than ethical field report, it focuses on curiosity, scientific humility, bodily adaptation, and what explorers owe to the worlds they study. (via @ohhushreads on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (198, NULL, 'On the Calculation of Volume, Book I', 'Solvej Balle', 2024, 160, 'A literary time-loop novel about Tara Selter, who becomes trapped repeating November 18 while everyone else continues unaware. The first of a seven-part sequence, it turns repetition into a study of attention, time, loneliness, routine, and perception. (via @ohhushreads on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (199, NULL, 'The Wax Child', 'Olga Ravn', 2025, 144, 'A brief, strange historical-literary novel rooted in 17th-century Danish witch-trial history. Ravn blends folklore, violence, female power, nature, magic, and archival horror into something closer to an incantation than a conventional historical novel. Longlisted for the International Booker Prize 2026. (via @ohhushreads on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (200, NULL, 'Audition', 'Katie Kitamura', 2025, 208, 'A taut literary novel about a middle-aged actress whose life destabilizes after a young man claims to be her son. It plays with performance, identity, motherhood, marriage, truth, and alternate versions of reality. (via @ohhushreads on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (201, NULL, 'Annie Bot', 'Sierra Greer', 2024, 240, 'A speculative literary novel about a female-presenting robot designed to be the ideal girlfriend for her owner. It reads as both AI story and feminist domestic-control story, exploring personhood, desire, coercion, and what it means to become self-aware. (via @ohhushreads on Instagram)', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;
